# architecture
arch: vit_base
enc_arch: MAEViTEncoder
dec_arch: MAEViTDecoder

# wandb
proj_name: gfpp-mae
run_name: ${proj_name}_${arch}_${dataset}
wandb_id:

# dataset
dataset: btcv
json_list: 'dataset_0.json'
data_path: ./data/BTCV

# output
output_dir: ./output/${run_name}
ckpt_dir: ${output_dir}/ckpts

# data preprocessing
space_x: 1.5
space_y: 1.5
space_z: 2.0
a_min: -175.0
a_max: 250.0
b_min: 0.0
b_max: 1.0
roi_x: 96
roi_y: 96
roi_z: 96
RandFlipd_prob: 0.2
RandRotate90d_prob: 0.2
RandScaleIntensityd_prob: 0.1
RandShiftIntensityd_prob: 0.1

# trainer
trainer_name: MAE3DTrainer
batch_size: 6
vis_batch_size: 1
start_epoch: 0
warmup_epochs: 100
epochs: 10000
workers: 1
resume:
test: False

# model
patchembed: 'PatchEmbed3D'
pos_embed_type: 'sincos'
input_size: 96
patch_size: 16
grid_size: [6, 6, 6]
in_chans: 1
encoder_embed_dim: 768
encoder_depth: 12
encoder_num_heads: 12
decoder_embed_dim: 384
decoder_depth: 8
decoder_num_heads: 12

mask_ratio: 0.50
b1: 0.01
b2: 1
b3: 20
b4: 1

# optimizer
type: adamw
lr: 6.4e-3
beta1: 0.9
beta2: 0.95
weight_decay: 0.05

# logging
vis_freq: 100
save_freq: 5000
print_freq: 1

# distributed processing
gpu: 0
dist_url:
world_size: 1
multiprocessing_distributed: false
dist_backend: nccl
distributed:
rank: 0
ngpus_per_node:

# randomness
seed: 1234

# debugging
debug: false